Lista de precios:
El precio de venta de 3 artículos en la venta de pasteles es: $2 por un brownie, $1 por una galleta y $10 por un pastel. Asignen estos valores a una lista denominada price (precio).

In [ ]:
price = [2, 1, 10]
type(price)

list

Lista de cantidad:

El club vende 17 brownies, 40 galletas y un pastel.  

Asignen estos valores a una lista denominada quantity_sold (cantidades vendidas).

In [ ]:
quantity_sold = [17, 40, 1]
type(quantity_sold)

list

Ahora debemos encontrar el dinero recaudado para cada tipo de elemento.  Queremos el precio * cantidad para cada elemento.  Tratemos de multiplicar nuestras listas. Intentar multiplicar dos listas juntas da lugar a un error y revela una debilidad crítica de las listas: Las listas no pueden manejar cálculos. ¡Los científicos de datos necesitan calcular! Para obtener el resultado que queremos, aprenderemos un nuevo tipo de datos llamado array de NumPy. El siguiente código importará la biblioteca NumPy.  También podemos usar un alias (abreviación) para la mayoría de las bibliotecas. Convencionalmente, a NumPy siempre se le asigna el alias "np".  

In [ ]:
import numpy as np

Convertir una lista a un array de NumPy

 Puesto que ya creamos listas para el precio y cantidad, podemos convertir estos a arrays usando el siguiente código:

In [ ]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

encontrar el dinero recaudado para cada tipo de elemento.  Queremos el precio * cantidad para cada elemento.

In [ ]:
price_array * quantity_sold_array

array([34, 40, 10])

A esto se le conoce como un cálculo elementwise (elemento a elemento).  Miremos otro ejemplo de cálculos elementwise.  Primero, creen un array de NumPy que corresponda al costo de fabricación de cada uno de los artículos vendidos en la venta de pasteles.  Digamos que cuesta $0,25 para hacer un brownie, una galleta, $0,50 y un pastel, $5,00

In [ ]:
cost_array = np.array([0.25, 0.50, 5.00])

Para encontrar la ganancia de cada artículo, queremos restar el costo del precio. Una matriz NumPy realizará la resta por elementos como se muestra

In [ ]:
profit_array = price_array - cost_array
print(profit_array)

[1.75 0.5  5.  ]


Booleanos elementwise

Supongamos que quieren identificar qué elementos obtuvieron un beneficio superior a $2 por elemento.  Pueden usar el siguiente código para preguntar si la declaración es True (verdadera) o False (falsa) para cada elemento en el array.

In [ ]:
profit_array > 2.00

array([False, False,  True])

Adición
El club también vende tartas por $7, así que debemos actualizar nuestro price_array.

In [ ]:
price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


También pueden añadir múltiples valores al array en un comando.
Por ejemplo, el club quiere agregar los siguientes precios: $4,50 por dulces, $3 por una magdalena, $4 por una barra de pan de plátano y $9 por una torta.  Observen el uso de corchetes en el siguiente código que añade inmediatamente los cuatro valores al array:

In [ ]:
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


Para comprobar el tipo de datos de los elementos del array, pueden utilizar lo siguiente:

In [ ]:
print(price_array.dtype)

float64


Eliminar

Resulta que nadie planea hacer una torta, así que quieren eliminar el precio de ese elemento del array.  Usaremos el comando np.delete(), pero necesitamos indicar qué elementos eliminar.  Usaremos la indexación (es muy similar a la indexación de las listas) para indicar que queremos eliminar el elemento en el índice 7 (recuerden usar indexación cero), o como es el último elemento, podemos ir por la derecha y utilizar el elemento -1.

In [ ]:
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


Reemplazar

Después el club decide subir el precio de los pasteles de $10 a $12.  Nuevamente, tendremos que identificar el elemento usando el índice.  Los pasteles están en el índice 2.

In [ ]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


Ejercicio Numpy de la panaderia

2 - Actualicen el quantity_sold_array para incluir la venta de 2 tartas, 3 bandejas de dulces, 16 magdalenas y 5 panes de plátano.  También se darán cuenta que una de las galletas que pensaron que se había vendido en realidad se cayó al suelo, así que editen quantity_sold_array de 40 a 39

In [ ]:
quantity_sold_array = np.append(quantity_sold_array,[2, 3, 16, 5])
print(quantity_sold_array)

[17 40  1  2  3 16  5]


In [ ]:
quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1  2  3 16  5]


3 - Determinen la cantidad de dinero recaudado de la venta de cada elemento en la venta de la panadería.

In [ ]:
quantity_money_collected_item = price_array * quantity_sold_array
print(quantity_money_collected_item)

[34.  39.  12.  14.  13.5 48.  20. ]


4 - Creen un array de NumPy "quantity_leftover" que incluya la cantidad de cada elemento restante al final de la venta: 2 pasteles, 1 tarta, 6 bandejas de dulces, 2 panes de plátano.  Pista: Asegúrense de incluir “0” de cada elemento que se haya vendido. ¿Por qué esto es importante cuando se crea un array?

Respuesta: Es importante porque al realizar cálculos entre elementos, estos calculos se realizan en orden, elemento a elemento. Es por ello que en el ejemplo se debe rellenar con 0, los elementos no vendidos.

In [ ]:
quantity_leftover_array = np.array([0, 0, 2, 1, 6, 0, 2])

5 - El club decide vender los elementos restantes a mitad de precio, y todo se venda rápidamente.  Determinen cuanto dinero se recaudó de la venta de liquidación.  

In [ ]:
quantity_money_collected_item_liquidation = (price_array * quantity_leftover_array) / 2
print(quantity_money_collected_item_liquidation)

[ 0.   0.  12.   3.5 13.5  0.   4. ]


In [ ]:
quantity_money_collected_item_liquidation = np.sum(quantity_money_collected_item_liquidation)
print(quantity_money_collected_item_liquidation)

33.0


6 - ¿Cuánto dinero total se recaudó de la venta de panadería (incluido la venta del precio total y los elementos liquidados)?

Pista: La respuesta final debería ser de $213.50, pero deben asegurarse de obtener esta respuesta con sus conocimientos de codificación de NumPy.

Suban un archivo con sus códigos y las soluciones.

In [ ]:
total_money_collected_sales = quantity_money_collected_item_liquidation + np.sum(quantity_money_collected_item)
print(total_money_collected_sales)

213.5
